stages:
  - lint
  - test
include:
  - component: $CI_SERVER_FQDN/ptrck-sh/templates/ci-templates/base@0.22.2
    inputs:
      runner_tags:
        - homelab
  - component: $CI_SERVER_FQDN/ptrck-sh/templates/ci-templates/pre-commit@0.22.2
  - component: $CI_SERVER_FQDN/ptrck-sh/templates/ci-templates/security@0.22.2
  - component: $CI_SERVER_FQDN/ptrck-sh/templates/ci-templates/alint-fix@0.22.2
