---
- include_tasks: gh.yml
  tags: ["dev", "gh"]

- name: "Install core packages"
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - wget
      - gettext
      - unzip
      - zip
      - jq
      - yq
      - git
      - tmux
      - net-tools
      - gnupg2
      - lua5.1
      - xdg-utils
      - yamllint
      - stow
      - build-essential
      - pkg-config
      - libfontconfig
      - software-properties-common
  tags:
    - install
    - core

- name: "Install dev packages"
  become: true
  ansible.builtin.apt:
    name:
      # - ffmpeg
      - apache2-utils
      - imagemagick
      - cmake
      - nmap
      - fontconfig
      - libtool
      - libtool-bin
      # - wslu
  tags:
    - install
    - core
    - dev
