---
- name: Get dotfiles repo
  ansible.builtin.git:
    repo: git@github.com:ppfenning92/dotfiles.git
    dest: "{{ ansible_env.HOME }}/.dotfiles"
    recursive: true
    update: true
    force: true

- name: Remove default .bashrc
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: absent

- name: Stow
  ansible.builtin.command: chdir={{ ansible_env.HOME }}/.dotfiles stow . -d . -t "{{ ansible_env.HOME }}"

- name: Create sudoers drop-in for admin_flag (Linux)
  become: true
  ansible.builtin.file:
    path: /etc/sudoers.d/disable_admin_flag
    state: touch
    mode: "644"
  when: is_linux | bool

- name: Disable admin_flag in sudoers (Linux)
  become: true
  ansible.builtin.blockinfile:
    marker: "### ANSIBLE MANAGED"
    path: /etc/sudoers.d/disable_admin_flag
    insertafter: EOF
    block: |
      Defaults !admin_flag
  when: is_linux | bool
