---
# On macOS kubectl comes from Homebrew (kubernetes-cli). Linux only.
- name: Get latest kubectl version
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: kubectl_version
  when: ansible_facts['os_family'] != 'Darwin'
  tags: &kubectl_tags ["dev", "kubectl"]

- name: Get kubectl binary checksum
  vars:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
  ansible.builtin.uri:
    url: "https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/{{ arch }}/kubectl.sha256"
    return_content: true
  register: kubectl_checksum
  when: ansible_facts['os_family'] != 'Darwin'
  tags: *kubectl_tags

- name: Download kubectl binary
  become: true
  vars:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/{{ kubectl_version.content }}/bin/linux/{{ arch }}/kubectl
    dest: /usr/local/bin/kubectl
    checksum: "sha256:{{ kubectl_checksum.content }}"
    mode: "0755"
  when: ansible_facts['os_family'] != 'Darwin'
  tags: *kubectl_tags
