---
- name: Ensure directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"
  tags:
    - ssh
    - dev

- name: Copy public key
  ansible.builtin.copy:
    dest: "{{ dest_key_pub }}"
    src: "{{ source_key_pub }}"
    mode: "0644"
  tags:
    - ssh
    - dev

- name: Copy private key
  ansible.builtin.copy:
    dest: "{{ dest_key }}"
    src: "{{ source_key }}"
    mode: "0600"
  tags:
    - ssh
    - dev

- name: Suppress last login line in SSH banner
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PrintLastLog'
    line: 'PrintLastLog no'
  register: sshd_config_changed
  when: is_debian | bool
  tags: [ssh]

- name: Restart ssh after config change
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted
  when: is_debian | bool and sshd_config_changed.changed
  tags: [ssh]

- name: Set git known_hosts
  ansible.builtin.shell: |
    ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
  tags:
    - ssh
    - dev
