---
- name: Install Homebrew
  ansible.builtin.shell: |
    set -o pipefail
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /opt/homebrew/bin/brew
  environment:
    NONINTERACTIVE: "1"
  tags: ["homebrew", "core"]
