---
- name: Get latest glab release
  ansible.builtin.uri:
    url: https://gitlab.com/api/v4/projects/gitlab-org%2Fcli/releases
    return_content: true
  register: glab_releases
  tags: &glab_tags ["dev", "glab"]

- name: Set glab version and platform facts
  vars:
    arch_map:
      x86_64: amd64
      aarch64: arm64
      arm64: arm64
    os_map:
      Debian: linux
      Ubuntu: linux
      Darwin: darwin
  ansible.builtin.set_fact:
    glab_version: "{{ (glab_releases.json | first).name }}"
    glab_arch: "{{ arch_map[ansible_architecture] | default(ansible_architecture) }}"
    glab_os: "{{ os_map[ansible_facts['os_family']] | default('linux') }}"
  tags: *glab_tags

- name: Get glab checksums
  ansible.builtin.uri:
    url: "https://gitlab.com/gitlab-org/cli/-/releases/{{ glab_version }}/downloads/checksums.txt"
    return_content: true
  register: glab_checksums
  tags: *glab_tags

- name: Set glab checksum
  ansible.builtin.set_fact:
    glab_checksum: "{{ item.split(' ')[0] }}"
  loop: "{{ glab_checksums.content.split('\n') }}"
  when: >
    'glab_' + (glab_version | regex_replace('^v', '')) + '_' + glab_os + '_' + glab_arch + '.tar.gz'
    in item
  tags: *glab_tags

- name: Download glab archive
  become: true
  ansible.builtin.get_url:
    url: "https://gitlab.com/gitlab-org/cli/-/releases/{{ glab_version }}/downloads/glab_{{ glab_version | regex_replace('^v', '') }}_{{ glab_os }}_{{ glab_arch }}.tar.gz"
    dest: /tmp/glab.tar.gz
    checksum: "sha256:{{ glab_checksum }}"
  tags: *glab_tags

- name: Unpack glab binary
  become: true
  ansible.builtin.unarchive:
    src: /tmp/glab.tar.gz
    dest: /usr/local/bin
    extra_opts: ["bin/glab", "--strip-components=1"]
    remote_src: true
    mode: "0755"
  tags: *glab_tags

- name: Remove glab install archive
  ansible.builtin.file:
    path: /tmp/glab.tar.gz
    state: absent
  tags: *glab_tags
