---
- name: Install XDG Ninja
  become: true
  changed_when: true
  ansible.builtin.git:
    repo: https://github.com/b3nj5m1n/xdg-ninja.git
    depth: 1
    dest: /opt/xdg-ninja
    update: true
    force: true
  tags: ["dev", "tool"]

- name: Prepare httpie install
  become: true
  vars:
    arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else ansible_architecture }}"
  ansible.builtin.shell: |
    curl -SsL https://packages.httpie.io/deb/KEY.gpg | gpg --dearmor --yes -o /usr/share/keyrings/httpie.gpg
    echo "deb [arch={{ arch }} signed-by=/usr/share/keyrings/httpie.gpg] https://packages.httpie.io/deb ./" > /etc/apt/sources.list.d/httpie.list
  tags: ["dev", "tool"]

- name: Install httpie
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - httpie
  tags: ["dev", "tool"]
