---
- name: Add 1Password apt key
  become: true
  ansible.builtin.shell: |
    curl -sS https://downloads.1password.com/linux/keys/1password.asc \
      | gpg --yes --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/1password-archive-keyring.gpg

- name: Add 1Password apt repository
  become: true
  ansible.builtin.shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] \
      https://downloads.1password.com/linux/debian/$(dpkg --print-architecture) stable main" \
      > /etc/apt/sources.list.d/1password.list
  args:
    creates: /etc/apt/sources.list.d/1password.list

- name: Create debsig policy directory
  become: true
  ansible.builtin.file:
    path: /etc/debsig/policies/AC2D62742012EA22
    state: directory
    mode: "0755"

- name: Deploy debsig policy
  become: true
  ansible.builtin.get_url:
    url: https://downloads.1password.com/linux/debian/debsig/1password.pol
    dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
    mode: "0644"

- name: Create debsig keyring directory
  become: true
  ansible.builtin.file:
    path: /usr/share/debsig/keyrings/AC2D62742012EA22
    state: directory
    mode: "0755"

- name: Add debsig key
  become: true
  ansible.builtin.shell: |
    curl -sS https://downloads.1password.com/linux/keys/1password.asc \
      | gpg --yes --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
  args:
    creates: /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg

- name: Install 1password-cli
  become: true
  ansible.builtin.apt:
    name: 1password-cli
    update_cache: true
    state: present
